#!/bin/bash

XBMC_SETTING_FOLDER="/root/.xbmc/userdata/"
GUISETTING=$XBMC_SETTING_FOLDER"guisettings.xml"
GUISETTING_TLBB=$XBMC_SETTING_FOLDER"guisettings_tlbb.xml"

if [ -f "$GUISETTING_TLBB" ]
then
	echo "copying $GUISETTING_TLBB to $GUISETTING found."
	cp -f $GUISETTING_TLBB $GUISETTING
	rm -f $GUISETTING_TLBB
else
	echo "$GUISETTING_TLBB not found."
fi
